### ISSUE TITLE
Custom CSV Delimiter Character

### ISSUE THREAD

**Issue by fahmijafar** [jogetoss/export-csv-or-excel#3]
Some of the data contains commas as values. Therefore, when exporting it using this plugin and reading it with MS Excel, the data becomes jumbled. We anticipate the inclusion of a feature for a Custom CSV delimiter character, similar to the one found in the Import Menu plugin.

**Comment by imranjoget** [comment]
Its fixed in 8.0.2 release. Added configuration for the delimiter. You can now specify any  delimiter of choice. 
If the delimiter value is empty, it will be set to ; default.
